# lid_topic: The topic name of LiDAR data.
# imu_topic: The topic name of IMU data.
# img_topic: The topic name of camera data.
# img_enable: Enbale vio submodule.
# lidar_enable: Enbale lio submodule.
# point_filter_num: The sampling interval for a new scan. It is recommended that 3~4 for faster odometry, 1~2 for denser map.
# outlier_threshold: The outlier threshold value of photometric error (square) of a single pixel. 
#                       It is recommended that 50~250 for the darker scenes, 500~1000 for the brighter scenes. 
#                       The smaller the value is, the faster the vio submodule is, but the weaker the anti-degradation ability is.
# img_point_cov: The covariance of photometric errors per pixel.
# laser_point_cov: The covariance of point-to-plane redisual per point.
# filter_size_surf: Downsample the points in a new scan. It is recommended that 0.05~0.15 for indoor scenes, 0.3~0.5 for outdoor scenes.
# filter_size_map: Downsample the points in LiDAR global map. It is recommended that 0.15~0.3 for indoor scenes, 0.4~0.5 for outdoor scenes.
feature_extract_enable : 0
point_filter_num : 1
max_iteration : 1
dense_map_enable : 1
filter_size_surf : 0.1
filter_size_map : 0.3
cube_side_length : 1000
debug : 0
grid_size : 40
patch_size : 8
img_enable : 0
lidar_enable : 1
outlier_threshold : 300 # 78 100 156
ncc_en: false
ncc_thre: 0
img_point_cov : 100 # 1000
laser_point_cov : 0.1 # 0.001
cam_fx: 890.3316568488494
cam_fy: 889.4658990090478
cam_cx: 505.888714925963
cam_cy: 387.46983397656777
  
map_file_path: "/home/zzwu/Desktop/ws_fast_livo/src/FAST-LIVO/Pcd"

common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/imu0"

preprocess:
    lidar_type: 4 # Livox mid-70 (pointcloud2 type)
    scan_line: 6
    blind: 5 # blind x m disable

mapping:
    acc_cov_scale: 100
    gyr_cov_scale: 1
    fov_degree:    90
    # extrinsic_T: [ -0.0683, 0.9215, 0.1998 ]
    # extrinsic_R: [ 0, -1, 0,
    #                1, 0, 0,
    #                0, 0, 1]

    # fast-lio2 calib
    extrinsic_T: [-0.067730 , 0.896803 , 0.195089]
    extrinsic_R: [  0.0600004295024988   ,     -0.998171734857471  ,     0.00728945753414962,
                    0.998198351057833    ,    0.0599986823957257   ,  -0.000458318885381425,
                0.0000201231095105464    ,   0.00730382382066623   ,      0.999973326520591 ]

camera:
    # img_topic: /usb_cam/image_raw
    # img_topic:  /camera/image_color
    img_topic: /cam0/image_raw
    #xiyuan
    Rcl: [0.00162756,-0.999991,0.00390957,
         -0.0126748,-0.00392989,-0.999912,
          0.999918,0.00157786,-0.012681]
    Pcl: [0.0409257, 0.0318424, -0.0927219]
    
